# Generated by Django 3.2.6 on 2021-08-03 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210803_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-posted',)},
        ),
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('-posted',)},
        ),
    ]
